name: kutanda_plant_auction
description: "A Flutter-based plant auction platform."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

# Add this to your dependencies section in pubspec.yaml:
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  image_picker: ^1.0.7
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.2
  cupertino_icons: ^1.0.8
  pinput: ^4.0.0
  provider: 6.0.5
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  supabase_flutter: ^2.8.3
  intl: ^0.18.1
  flutter_local_notifications: ^13.0.0
  onesignal_flutter: ^5.0.4
  flutter_dotenv: ^5.0.2
  uni_links: ^0.5.1
  # Authentication
  # UI & Icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/