import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:kutanda/lib/services/api_service.dart'; // Ensure this path is correct

// Generate mocks by running `flutter pub run build_runner build`
@GenerateMocks([SupabaseClient, GoTrueClient, SupabaseFunctions, FlutterSecureStorage, User, FunctionResponse])
import 'api_service_test.mocks.dart'; // This file will be generated by Mockito

void main() {
  late ApiService apiService;
  late MockSupabaseClient mockSupabaseClient;
  late MockGoTrueClient mockGoTrueClient;
  late MockSupabaseFunctions mockSupabaseFunctions;
  late MockFlutterSecureStorage mockSecureStorage;
  late MockUser mockUser;

  setUp(() {
    mockSupabaseClient = MockSupabaseClient();
    mockGoTrueClient = MockGoTrueClient();
    mockSupabaseFunctions = MockSupabaseFunctions();
    mockSecureStorage = MockFlutterSecureStorage();
    mockUser = MockUser();

    // Mock the Supabase instance to return our mockSupabaseClient
    // This is a common way to mock the global Supabase.instance.client
    // However, ApiService directly news SupabaseClient, so we might need to inject it or refactor ApiService.
    // For now, let's assume ApiService can be instantiated with a SupabaseClient for testing.
    // If not, this setup will need adjustment. The current ApiService news its own Supabase.instance.client.
    // This makes it hard to test without a refactor or a more complex mocking strategy for Supabase.instance.

    // Let's try to mock the global instance if ApiService is not refactored for DI.
    // This is tricky and might not work as expected without further setup.
    // A better approach is to refactor ApiService to accept SupabaseClient via constructor.
    
    // For now, we will proceed by directly instantiating ApiService and mocking its internal Supabase client's parts.
    // This requires that when `Supabase.instance.client` is called within ApiService, it's our mock.
    // This is difficult. Let's assume we can refactor ApiService or find a way to inject.
    // Given the current structure of ApiService, I will mock the chain of calls.

    // NOW: ApiService is refactored to accept SupabaseClient via constructor
    apiService = ApiService(supabaseInstance: mockSupabaseClient);

    // Mocking chain for Supabase calls
    when(mockSupabaseClient.auth).thenReturn(mockGoTrueClient);
    when(mockSupabaseClient.functions).thenReturn(mockSupabaseFunctions);

    // Simulate that ApiService uses this mocked client.
    // This is the problematic part if Supabase.instance.client cannot be easily replaced globally for tests.
    // A common pattern is to have a singleton wrapper for Supabase that can be replaced in tests.
    // Or, as mentioned, constructor injection for ApiService.

    // For the purpose of this test, we will assume that when apiService calls
    // supabase.auth or supabase.functions, it eventually uses our mocks.
    // This will be achieved by mocking the Supabase.instance getter if possible,
    // or by focusing on what ApiService *does* with the client.

    // Let's assume ApiService is refactored to take SupabaseClient in constructor for testability
    // Example: apiService = ApiService(mockSupabaseClient);
    // Since it's not, we have to rely on mocking what it calls if Supabase.instance can't be mocked globally.

    // For the existing ApiService structure:
    // We need to ensure that when `Supabase.instance.client` is called inside ApiService,
    // it returns our `mockSupabaseClient`. This is the tricky part.
    // One way is to use a package that allows mocking static/global instances, or refactor ApiService.

    // Let's simplify and assume that the `Supabase.instance.client` calls within ApiService
    // can be intercepted or that ApiService is refactored.
    // For this exercise, I will write the tests as if `apiService.supabase` can be made to use `mockSupabaseClient`.
    // This often means `apiService.supabase = mockSupabaseClient;` if `supabase` is public, or constructor injection.
    // The provided ApiService news its own client: `final SupabaseClient supabase = Supabase.instance.client;`
    // This is hard to mock directly.

    // The tests will be written assuming that calls to `apiService.supabase.auth` and `apiService.supabase.functions`
    // are correctly routed to `mockGoTrueClient` and `mockSupabaseFunctions`.
    // This is a common challenge with static/singleton access in testing.
  });

  group('ApiService PUT Requests', () {
    final testEndpoint = 'test-put-endpoint';
    final testData = {'key': 'value'};
    final mockSuccessResponse = MockFunctionResponse();
    final mockErrorResponse = MockFunctionResponse();

    setUp(() {
      // Reset mocks for each test
      reset(mockGoTrueClient);
      reset(mockSupabaseFunctions);
      reset(mockSuccessResponse);
      reset(mockErrorResponse);
      
      // Common stubbing for auth and functions client
      when(mockSupabaseClient.auth).thenReturn(mockGoTrueClient);
      when(mockSupabaseClient.functions).thenReturn(mockSupabaseFunctions);

      // Mock successful response
      when(mockSuccessResponse.status).thenReturn(200);
      when(mockSuccessResponse.data).thenReturn({'status': 'success', 'data': 'put_success_data'});

      // Mock error response
      when(mockErrorResponse.status).thenReturn(500);
      when(mockErrorResponse.data).thenReturn({'status': 'error', 'message': 'server_error'});
    });

    test('put returns data on successful request (200)', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.put, body: testData))
          .thenAnswer((_) async => mockSuccessResponse);

      final result = await apiService.put(testEndpoint, testData);

      expect(result, isNotNull);
      expect(result!['status'], 'success');
      expect(result['data'], 'put_success_data');
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.put, body: testData)).called(1);
    });

    test('put returns null when user is not authenticated', () async {
      when(mockGoTrueClient.currentUser).thenReturn(null);

      final result = await apiService.put(testEndpoint, testData);

      expect(result, isNull);
      verifyNever(mockSupabaseFunctions.invoke(any, method: anyNamed('method'), body: anyNamed('body')));
    });

    test('put returns null when API returns non-200 status', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.put, body: testData))
          .thenAnswer((_) async => mockErrorResponse);

      final result = await apiService.put(testEndpoint, testData);

      expect(result, isNull);
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.put, body: testData)).called(1);
    });

    test('put returns null when invoke throws an exception', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.put, body: testData))
          .thenThrow(Exception('Network error'));

      final result = await apiService.put(testEndpoint, testData);

      expect(result, isNull);
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.put, body: testData)).called(1);
    });
  });

  group('ApiService DELETE Requests', () {
    final testEndpoint = 'test-delete-endpoint';
    final testData = {'key': 'value'}; // Optional data for delete
    final mockSuccessResponse = MockFunctionResponse();
    final mockErrorResponse = MockFunctionResponse();

    setUp(() {
      reset(mockGoTrueClient);
      reset(mockSupabaseFunctions);
      reset(mockSuccessResponse);
      reset(mockErrorResponse);
      
      when(mockSupabaseClient.auth).thenReturn(mockGoTrueClient);
      when(mockSupabaseClient.functions).thenReturn(mockSupabaseFunctions);

      when(mockSuccessResponse.status).thenReturn(200);
      when(mockSuccessResponse.data).thenReturn({'status': 'success', 'data': 'delete_success_data'});

      when(mockErrorResponse.status).thenReturn(500);
      when(mockErrorResponse.data).thenReturn({'status': 'error', 'message': 'server_error'});
    });

    test('delete returns data on successful request (200, with data)', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.delete, body: testData))
          .thenAnswer((_) async => mockSuccessResponse);

      final result = await apiService.delete(testEndpoint, data: testData);

      expect(result, isNotNull);
      expect(result!['status'], 'success');
      expect(result['data'], 'delete_success_data');
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.delete, body: testData)).called(1);
    });

    test('delete returns data on successful request (200, without data)', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.delete, body: null)) // body is null
          .thenAnswer((_) async => mockSuccessResponse);

      final result = await apiService.delete(testEndpoint); // No data passed

      expect(result, isNotNull);
      expect(result!['status'], 'success');
      expect(result['data'], 'delete_success_data');
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.delete, body: null)).called(1);
    });

    test('delete returns null when user is not authenticated', () async {
      when(mockGoTrueClient.currentUser).thenReturn(null);

      final result = await apiService.delete(testEndpoint, data: testData);

      expect(result, isNull);
      verifyNever(mockSupabaseFunctions.invoke(any, method: anyNamed('method'), body: anyNamed('body')));
    });

    test('delete returns null when API returns non-200 status', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.delete, body: testData))
          .thenAnswer((_) async => mockErrorResponse);

      final result = await apiService.delete(testEndpoint, data: testData);

      expect(result, isNull);
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.delete, body: testData)).called(1);
    });

    test('delete returns null when invoke throws an exception', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.delete, body: testData))
          .thenThrow(Exception('Network error'));

      final result = await apiService.delete(testEndpoint, data: testData);

      expect(result, isNull);
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.delete, body: testData)).called(1);
    });
  });

  group('ApiService PATCH Requests', () {
    final testEndpoint = 'test-patch-endpoint';
    final testData = {'key': 'value_patched'};
    final mockSuccessResponse = MockFunctionResponse();
    final mockErrorResponse = MockFunctionResponse();

    setUp(() {
      reset(mockGoTrueClient);
      reset(mockSupabaseFunctions);
      reset(mockSuccessResponse);
      reset(mockErrorResponse);

      when(mockSupabaseClient.auth).thenReturn(mockGoTrueClient);
      when(mockSupabaseClient.functions).thenReturn(mockSupabaseFunctions);

      when(mockSuccessResponse.status).thenReturn(200);
      when(mockSuccessResponse.data).thenReturn({'status': 'success', 'data': 'patch_success_data'});

      when(mockErrorResponse.status).thenReturn(500);
      when(mockErrorResponse.data).thenReturn({'status': 'error', 'message': 'server_error'});
    });

    test('patch returns data on successful request (200)', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.patch, body: testData))
          .thenAnswer((_) async => mockSuccessResponse);

      final result = await apiService.patch(testEndpoint, testData);

      expect(result, isNotNull);
      expect(result!['status'], 'success');
      expect(result['data'], 'patch_success_data');
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.patch, body: testData)).called(1);
    });

    test('patch returns null when user is not authenticated', () async {
      when(mockGoTrueClient.currentUser).thenReturn(null);

      final result = await apiService.patch(testEndpoint, testData);

      expect(result, isNull);
      verifyNever(mockSupabaseFunctions.invoke(any, method: anyNamed('method'), body: anyNamed('body')));
    });

    test('patch returns null when API returns non-200 status', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.patch, body: testData))
          .thenAnswer((_) async => mockErrorResponse);

      final result = await apiService.patch(testEndpoint, testData);

      expect(result, isNull);
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.patch, body: testData)).called(1);
    });

    test('patch returns null when invoke throws an exception', () async {
      when(mockGoTrueClient.currentUser).thenReturn(mockUser);
      when(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.patch, body: testData))
          .thenThrow(Exception('Network error'));

      final result = await apiService.patch(testEndpoint, testData);

      expect(result, isNull);
      verify(mockSupabaseFunctions.invoke(testEndpoint, method: HttpMethod.patch, body: testData)).called(1);
    });
  });
}
